### ISSUE TITLE
A question about the project

### ISSUE THREAD

**Issue by egorsmkv** [cemsbr/browscap#22]
Hello @cemsbr 

Is it still in development stage?

**Comment by cemsbr** [comment]
It's not in my priority list, but this question may be a motivation to resume the development :)

**Comment by egorsmkv** [comment]
It will be cool if you make a stable release, because the browscap database is very good source to parse users agents. I did not find another library to work with the browscap database.

**Comment by cemsbr** [comment]
Ok, I'll reserve a few hours to make the first release.

**Comment by egorsmkv** [comment]
Thanks!
